version: "3.9"

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.nextjs
    container_name: interactive-board
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_CONVEX_URL: ${NEXT_PUBLIC_CONVEX_URL}
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      NEXT_PUBLIC_LIVEBLOCKS_PUBLIC_KEY: ${NEXT_PUBLIC_LIVEBLOCKS_PUBLIC_KEY}
      LIVEBLOCKS_SECRET_KEY: ${LIVEBLOCKS_SECRET_KEY}
    ports:
      - "3030:3000"
    networks:
      - proxy

networks:
  proxy:
    external: true
