version: "3.9"

services:
  interactive-board:
    build:
      context: .
      dockerfile: Dockerfile.nextjs
    container_name: interactive-board
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3030:3000"
    networks:
      - proxy
    user: "1001:1001"
    working_dir: /app
    command: ["npm", "start"]

networks:
  proxy:
    external: true
